export const TICKET_TYPE = {
  ACCOUNT: 'ACCOUNT',
  BILLING: 'BILLING',
  ORGANIZATION: 'ORGANIZATION',
  CUSTOMIZING: 'CUSTOMIZING',
};

export const TICKET_SUBTYPE = {
  ACCOUNT_REGISTRATION: 'ACCOUNT_REGISTRATION',
  ACCOUNT_PRIVACY: 'ACCOUNT_PRIVACY',
  ACCOUNT_NOTIFICATIONS: 'ACCOUNT_NOTIFICATIONS',
  ACCOUNT_DEACTIVATION: 'ACCOUNT_DEACTIVATION',
  UPDATE_VERIFY_PROFILE: 'UPDATE_VERIFY_PROFILE',
  INDIVIDUAL_RECRUITER_ACCOUNT: 'INDIVIDUAL_RECRUITER_ACCOUNT',
  ACCOUNT_AUTHENTICATION: 'ACCOUNT_AUTHENTICATION',
  MANAGE_PREMIUM_ACCOUNT: 'MANAGE_PREMIUM_ACCOUNT',
  ACCOUNT_RESTRICTIONS: 'ACCOUNT_RESTRICTIONS',

  BILLING_OVERVIEW: 'BILLING_OVERVIEW',
  PAYMENT_METHODS: 'PAYMENT_METHODS',
  INVOICES: 'INVOICES',
  SUBSCRIPTION_PLANS: 'SUBSCRIPTION_PLANS',
  PAYMENT_SECURITY: 'PAYMENT_SECURITY',
  PAYMENT_PROCESS: 'PAYMENT_PROCESS',
  REFUND_POLICY: 'REFUND_POLICY',
  PROMOTIONS_AND_DISCOUNT_CODES: 'PROMOTIONS_AND_DISCOUNT_CODES',
  COMMON_PAYMENT_ERRORS: 'COMMON_PAYMENT_ERRORS',

  ORG_SEARCH: 'ORG_SEARCH',
  ORG_PROFILE: 'ORG_PROFILE',
  CREATE_AND_MANAGE_ORG: 'CREATE_AND_MANAGE_ORG',
  INVITE_AND_MANAGE_TEAM_MEMBERS: 'INVITE_AND_MANAGE_TEAM_MEMBERS',
  USER_ROLES_AND_PERMISSIONS: 'USER_ROLES_AND_PERMISSIONS',
  SETTING_UP_ORG_STRUCTURE: 'SETTING_UP_ORG_STRUCTURE',
  KYC: 'KYC',

  CUSTOMIZE_FEED_AND_JOB_SUGGESTIONS: 'CUSTOMIZE_FEED_AND_JOB_SUGGESTIONS',
  SETTING_DISPLAY_LANGUAGE_AND_TIME_ZONE: 'SETTING_DISPLAY_LANGUAGE_AND_TIME_ZONE',
  MANAGING_YOUR_NOTIFICATION_PREFERENCES: 'MANAGING_YOUR_NOTIFICATION_PREFERENCES',
  DARK_MODE_AND_DISPLAY_SETTINGS: 'DARK_MODE_AND_DISPLAY_SETTINGS',
  CUSTOMIZING_PROFILE_VISIBILITY_AND_PUBLIC_VIEW: 'CUSTOMIZING_PROFILE_VISIBILITY_AND_PUBLIC_VIEW',
  PERSONALIZING_RESUME_AND_JOB_APPLICATION_SETTINGS:
    'PERSONALIZING_RESUME_AND_JOB_APPLICATION_SETTINGS',
};

export const TYPE_TO_SUBTYPE = {
  [TICKET_TYPE.ACCOUNT]: [
    TICKET_SUBTYPE.ACCOUNT_REGISTRATION,
    TICKET_SUBTYPE.ACCOUNT_PRIVACY,
    TICKET_SUBTYPE.ACCOUNT_NOTIFICATIONS,
    TICKET_SUBTYPE.ACCOUNT_DEACTIVATION,
    TICKET_SUBTYPE.UPDATE_VERIFY_PROFILE,
    TICKET_SUBTYPE.INDIVIDUAL_RECRUITER_ACCOUNT,
    TICKET_SUBTYPE.ACCOUNT_AUTHENTICATION,
    TICKET_SUBTYPE.MANAGE_PREMIUM_ACCOUNT,
    TICKET_SUBTYPE.ACCOUNT_RESTRICTIONS,
  ],
  [TICKET_TYPE.BILLING]: [
    TICKET_SUBTYPE.BILLING_OVERVIEW,
    TICKET_SUBTYPE.PAYMENT_METHODS,
    TICKET_SUBTYPE.INVOICES,
    TICKET_SUBTYPE.SUBSCRIPTION_PLANS,
    TICKET_SUBTYPE.PAYMENT_SECURITY,
    TICKET_SUBTYPE.PAYMENT_PROCESS,
    TICKET_SUBTYPE.REFUND_POLICY,
    TICKET_SUBTYPE.PROMOTIONS_AND_DISCOUNT_CODES,
    TICKET_SUBTYPE.COMMON_PAYMENT_ERRORS,
  ],
  [TICKET_TYPE.ORGANIZATION]: [
    TICKET_SUBTYPE.ORG_SEARCH,
    TICKET_SUBTYPE.ORG_PROFILE,
    TICKET_SUBTYPE.CREATE_AND_MANAGE_ORG,
    TICKET_SUBTYPE.INVITE_AND_MANAGE_TEAM_MEMBERS,
    TICKET_SUBTYPE.USER_ROLES_AND_PERMISSIONS,
    TICKET_SUBTYPE.SETTING_UP_ORG_STRUCTURE,
    TICKET_SUBTYPE.KYC,
  ],
  [TICKET_TYPE.CUSTOMIZING]: [
    TICKET_SUBTYPE.CUSTOMIZE_FEED_AND_JOB_SUGGESTIONS,
    TICKET_SUBTYPE.SETTING_DISPLAY_LANGUAGE_AND_TIME_ZONE,
    TICKET_SUBTYPE.MANAGING_YOUR_NOTIFICATION_PREFERENCES,
    TICKET_SUBTYPE.DARK_MODE_AND_DISPLAY_SETTINGS,
    TICKET_SUBTYPE.CUSTOMIZING_PROFILE_VISIBILITY_AND_PUBLIC_VIEW,
    TICKET_SUBTYPE.PERSONALIZING_RESUME_AND_JOB_APPLICATION_SETTINGS,
  ],
};

export const TICKET_TYPE_PREFIX_MAP = {
  [TICKET_TYPE.ACCOUNT]: 'AC',
  [TICKET_TYPE.BILLING]: 'BI',
  [TICKET_TYPE.ORGANIZATION]: 'OR',
  [TICKET_TYPE.CUSTOMIZING]: 'CU',
};

export enum TicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING = 'PENDING',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  REOPENED = 'REOPENED',
}

export enum Priority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}
