export const TICKET_TYPE = {
  ACCOUNT: 'ACCOUNT',
  BILLING: 'BILLING',
  ORGANIZATION: 'ORGANIZATION',
  CUSTOMIZING: 'CUSTOMIZING',
};

export const TICKET_SUBTYPE = {
  ACCOUNT_REGISTRATION: 'ACCOUNT_REGISTRATION',
  ACCOUNT_PRIVACY: 'ACCOUNT_PRIVACY',
  ACCOUNT_NOTIFICATIONS: 'ACCOUNT_NOTIFICATIONS',
  ACCOUNT_DEACTIVATION: 'ACCOUNT_DEACTIVATION',

  BILLING_OVERVIEW: 'BILLING_OVERVIEW',
  PAYMENT_METHODS: 'PAYMENT_METHODS',
  INVOICES: 'INVOICES',
  SUBSCRIPTION_PLANS: 'SUBSCRIPTION_PLANS',
  PAYMENT_SECURITY: 'PAYMENT_SECURITY',

  ORG_SEARCH: 'ORG_SEARCH',
  ORG_PROFILE: 'ORG_PROFILE',
  ACCESSIBLE_BANKING: 'ACCESSIBLE_BANKING',
  MOBILE_BANKING: 'MOBILE_BANKING',

  COLLEGE_PLANNING: 'COLLEGE_PLANNING',
  LEARN_CREDIT: 'LEARN_CREDIT',
  BUDGETING: 'BUDGETING',
  FUND_TRANSFER: 'FUND_TRANSFER',
};

export const TYPE_TO_SUBTYPE = {
  [TICKET_TYPE.ACCOUNT]: [
    TICKET_SUBTYPE.ACCOUNT_REGISTRATION,
    TICKET_SUBTYPE.ACCOUNT_PRIVACY,
    TICKET_SUBTYPE.ACCOUNT_NOTIFICATIONS,
    TICKET_SUBTYPE.ACCOUNT_DEACTIVATION,
  ],
  [TICKET_TYPE.BILLING]: [
    TICKET_SUBTYPE.BILLING_OVERVIEW,
    TICKET_SUBTYPE.PAYMENT_METHODS,
    TICKET_SUBTYPE.INVOICES,
    TICKET_SUBTYPE.SUBSCRIPTION_PLANS,
    TICKET_SUBTYPE.PAYMENT_SECURITY,
  ],
  [TICKET_TYPE.ORGANIZATION]: [
    TICKET_SUBTYPE.ORG_SEARCH,
    TICKET_SUBTYPE.ORG_PROFILE,
    TICKET_SUBTYPE.ACCESSIBLE_BANKING,
    TICKET_SUBTYPE.MOBILE_BANKING,
  ],
  [TICKET_TYPE.CUSTOMIZING]: [
    TICKET_SUBTYPE.COLLEGE_PLANNING,
    TICKET_SUBTYPE.LEARN_CREDIT,
    TICKET_SUBTYPE.BUDGETING,
    TICKET_SUBTYPE.FUND_TRANSFER,
  ],
};

export const TICKET_TYPE_PREFIX_MAP = {
  [TICKET_TYPE.ACCOUNT]: 'AC',
  [TICKET_TYPE.BILLING]: 'BI',
  [TICKET_TYPE.ORGANIZATION]: 'OR',
  [TICKET_TYPE.CUSTOMIZING]: 'CU',
};

export enum TicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING = 'PENDING',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  REOPENED = 'REOPENED',
}

export enum Priority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}
