export enum TicketType {
  ANALYTIC_REPORTING = 'ANALYTIC_REPORTING',
  JOB_ADVERTISING = 'JOB_ADVERTISING',
  MANAGE_COMPANY_PROFILE = 'MANAGE_COMPANY_PROFILE',
  PERSONAL_ACCOUNT = 'PERSONAL_ACCOUNT',
  PROFILE = 'PROFILE',
  SALARY_ESTIMATES = 'SALARY_ESTIMATES',
  SALES_INQUIRY = 'SALES_INQUIRY',
  COMPANY_REVIEWS = 'COMPANY_REVIEWS',
  SUBSCRIPTION_BILLING = 'SUBSCRIPTION_BILLING',
  TECHNICAL_SUPPORT = 'TECHNICAL_SUPPORT',
}

export const TICKET_TYPE_PREFIX_MAP = {
  [TicketType.ANALYTIC_REPORTING]: 'AR',
  [TicketType.JOB_ADVERTISING]: 'JA',
  [TicketType.MANAGE_COMPANY_PROFILE]: 'MCP',
  [TicketType.PERSONAL_ACCOUNT]: 'PA',
  [TicketType.PROFILE]: 'PR',
  [TicketType.SALARY_ESTIMATES]: 'SE',
  [TicketType.SALES_INQUIRY]: 'SI',
  [TicketType.COMPANY_REVIEWS]: 'CR',
  [TicketType.SUBSCRIPTION_BILLING]: 'SB',
  [TicketType.TECHNICAL_SUPPORT]: 'TS',
};

export enum TicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING = 'PENDING',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  REOPENED = 'REOPENED',
}

export enum Priority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}
